---

- hosts: "localhost"
  become: yes
  vars:
    base_path: '~/mc.config'

  tasks:
   - import_tasks: tasks/system-update.yml

   - import_tasks: tasks/install-opera.yml
   - import_tasks: tasks/install-sublime.yml
   - import_tasks: tasks/install-keepass.yml
   - import_tasks: tasks/install-common.yml
   - import_tasks: tasks/install-python37.yml

   - import_tasks: tasks/config-bashrc.yml
   - import_tasks: tasks/config-git.yml
