---

- stat: path=~/.gitconfig
  register: links


- name: 'Backup .gitcongig'
  command: mv ~/.gitconfig ~/.gitconfig.bkp
  ignore_errors: yes
  when: links.stat is defined and links.stat.islnk is not defined


- name: 'Configure .gitconfig'
  file:
    src: '{{ base_path }}/files/git/_gitconfig'
    path: ~/.gitconfig
    state: link
    owner: '{{user}}'
    mode: u=rwx,g=rwx,o-rwx