---

- name: 'Backup .gitcongig'
  command: mv ~/.gitconfig ~/.gitconfig.bkp
  ignore_errors: yes

- name: 'Configure .gitconfig'
  file:
    src: '{{ base_path }}/files/git/_gitconfig'
    path: ~/.gitconfig
    state: link