---

- name: 'Create folder ~/.config/'
  file:
    path: ~/.config/
    state: directory
    owner: '{{user}}'
    mode: u=rwx,g=rwx,o-rwx


- name: 'Backup ~/.config/user-dirs.dirs'
  ignore_errors: True
  command: mv ~/.config/user-dirs.dirs ~/.config/user-dirs.dirs.bkp


- name: 'Configure user-dirs'
  file:
    src: '{{base_path}}/files/user_dirs/user-dirs.dirs'
    path: ~/.config/user-dirs.dirs
    state: link
