---

# Add python ppa

# Not always works
# - name: 'Add deb repo ppa:deadsnakes/ppa'
#   apt_repository:
#     repo: ppa:deadsnakes/ppa
#     state: present
#     update_cache: yes

- name: 'Add deb repo ppa:deadsnakes/ppa'
  command: add-apt-repository ppa:deadsnakes/ppa -y



# Install python3.7 packages

- name: 'Install python3.7 packages'
  apt:
    package: ['software-properties-common', 'python3.7', 'python3.7-doc', 'python3.7-examples', 'python3-pip']
    state: present
    allow_unauthenticated: no
    update_cache: yes



# Remove old python symlinks

- name: 
  local_action: stat path=/usr/bin/python
  register: file

- name: 'Backup /usr/bin/python'
  copy:
    src: /usr/bin/python
    dest: /usr/bin/_python.bkp
  when: file.stat.exists

- name: 'Remove /usr/bin/python'
  file:
    path: /usr/bin/python
    state: absent
  when: file.stat.exists


- name: 
  local_action: stat path=/usr/bin/pip
  register: file

- name: 'Backup /usr/bin/pip'
  copy:
    src: /usr/bin/pip
    dest: /usr/bin/_pip.bkp
  when: file.stat.exists

- name: 'Remove /usr/bin/pip'
  file:
    path: /usr/bin/pip
    state: absent
  when: file.stat.exists


- name: 
  local_action: stat path=/usr/local/bin/pip
  register: file

- name: 'Backup /usr/local/bin/pip'
  copy:
    src: /usr/local/bin/pip
    dest: /usr/local/bin/_pip.bkp
  when: file.stat.exists

- name: 'Remove /usr/local/bin/pip'
  file:
    path: /usr/local/bin/pip
    state: absent
  when: file.stat.exists



# Create python altenatives

- name: 'Create linux alternative python_pip_local -> /usr/local/bin/pip'
  shell: |
    update-alternatives --remove  python_pip_local /usr/local/bin/pip
    update-alternatives --install "/usr/local/bin/pip" python_pip_local "/usr/bin/pip2" 100
    update-alternatives --install "/usr/local/bin/pip" python_pip_local "/usr/bin/pip3" 50
    update-alternatives --set python_pip_local "/usr/bin/pip2"
    update-alternatives --display python_pip_local
  ignore_errors: True
  become: true

- name: 'Create linux alternative python_pip_bin -> /usr/bin/pip'
  shell: |
    update-alternatives --remove  python_pip_bin /usr/bin/pip
    update-alternatives --install "/usr/bin/pip" python_pip_bin "/usr/bin/pip2" 100
    update-alternatives --install "/usr/bin/pip" python_pip_bin "/usr/bin/pip3" 50
    update-alternatives --set python_pip_bin "/usr/bin/pip2"
    update-alternatives --display python_pip_bin
  ignore_errors: True
  become: true

- name: 'Create linux alternative python -> /usr/bin/python'
  shell: |
    update-alternatives --remove  python /usr/bin/python
    update-alternatives --install "/usr/bin/python" python "/usr/bin/python2.7" 100
    update-alternatives --install "/usr/bin/python" python "/usr/bin/python3.7" 50
    update-alternatives --set python "/usr/bin/python2.7"
    update-alternatives --display python
  ignore_errors: True
  become: true

- name: 'Create linux alternative python3 -> /usr/bin/python3'
  shell: |
    update-alternatives --remove  python3 /usr/bin/python3
    update-alternatives --install "/usr/bin/python3" python3 "/usr/bin/python3.6" 100
    update-alternatives --install "/usr/bin/python3" python3 "/usr/bin/python3.7" 50
    update-alternatives --set python3 "/usr/bin/python3.6"
    update-alternatives --display python3
  ignore_errors: True
  become: true



# Info 

- name: 'Display python versions'
  shell: |
    python3.7 --version
    echo
    python3 --version
    echo
    python --version
    echo
    pip3 --version
    echo
    pip --version
  ignore_errors: True
