---


- name: Download opera archive.key
  get_url:
    url: https://deb.opera.com/archive.key
    dest: files/opera/archive.key


- name: Use apt-key with opera key
  ansible.builtin.command:
    cmd: apt-key add files/opera/archive.key
  args:
    warn: false


- name: 'Install opera source list file'
  copy:
    src: files/opera/opera.list
    dest: /etc/apt/sources.list.d/opera.list


- name: 'Install opera browser'
  apt:
    package: ['opera-stable']
    state: present
    allow_unauthenticated: no
    update_cache: yes


- name: 'Update opera launcher'
  copy:
    src: files/autostart/opera.desktop
    dest: /usr/share/applications/opera.desktop
    owner: 'root'
    mode: u=rw,g=r,o=r


- name: 'Install opera launcher'
  command: xdg-desktop-menu install --novendor /usr/share/applications/opera.desktop
  ignore_errors: yes
  when: linux_distro_name == 'ubuntu'


- stat: path=/usr/lib/x86_64-linux-gnu/opera/libffmpeg.so
  register: links


- name: Get custom date and time
  set_fact:
      file_datetime: "{{ '%Y-%m-%d_%H-%M-%S' | strftime }}"


- name: Display custom formatted date and time
  debug:
     msg: "Backup file date and time: {{ file_datetime }}"


- name: 'Backup libffmpeg.so'
  become: true
  command: mv /usr/lib/x86_64-linux-gnu/opera/libffmpeg.so /usr/lib/x86_64-linux-gnu/opera/libffmpeg.so.{{file_datetime}}.bkp
  ignore_errors: yes
  when: links.stat.exists and not links.stat.islnk


- name:  'Install chromium-ffmpeg'
  community.general.snap:
    name:
      - chromium-ffmpeg


- name: 'Find latest version on chromium-ffmpeg'
  ansible.builtin.find:
    paths: /snap/chromium-ffmpeg/current/
    file_type: directory
    patterns: 'chromium-ffmpeg-*'
  register: output


- name: 'Find latest libffmpeg.so version'
  set_fact:
    file_name: "{{ item.path }}/chromium-ffmpeg/libffmpeg.so"
  with_items: "{{ output.files }}"

- debug: var=file_name


- name: 'Update opera libffmpeg.so version'
  become: true
  file:
    src: '{{file_name}}'
    path: /usr/lib/x86_64-linux-gnu/opera/libffmpeg.so
    state: link
