---

- name: 'Install common ubuntu packages'
  apt:
    package: ['guake', 
              'ssh', 
              'sshfs', 
              'xcalib', 
              'sublime-text', 
              'blueman', 
              'thunderbird', 
              'aptitude', 
              'audacious', 
              'cheese', 
              'virtualbox', 
              'virtualbox-qt', 
              'openvpn', 
              'network-manager-openvpn', 
              'network-manager-openvpn-gnome', 
              'ktouch', 
              'winff', 
              'gparted', 
              'smplayer', 
              'gir1.2-gtop-2.0', 
              'blender', 
              'pepperflashplugin-nonfree',
              'dconf-editor', 
              'dconf-tools',
              'encfs',
              'spotify-client',
              'exiftool',
              'gimp']
    state: present
    allow_unauthenticated: no
    update_cache: yes


- name: 'Install mint-backgrounds'
  apt:
    package: ['mint-backgrounds-*']
    state: present
    allow_unauthenticated: no
    update_cache: yes


# - name: 'Uninstall unwanted ubuntu packages'
#   apt:
#     package: ['seahorse',
#               'linuxmint-keyring',
#               'ubuntu-dbgsym-keyring',
#               '*gnome-keyring',
#               'gnome-keyring-*']
#     state: absent
#     allow_unauthenticated: no
#     update_cache: yes


# Error packages:
# 'thunderbird-enigmail', 'gnome-search-tool'
