---

- name: 'Install keepass dependencies'
  apt:
    package: ['cmake',
              'g++',
              'build-essential',
              'qtbase5-dev', 
              'qttools5-dev',
              'qttools5-dev-tools',
              'libqt5svg5-dev',
              'libgcrypt20-dev',
              'libargon2-0-dev',
              'libqrencode-dev',
              'libsodium-dev',
              'zlib1g-dev']
    state: present
    allow_unauthenticated: no
    update_cache: yes

# Does not work properly
# FixMe: Resulting menu item has no icon

# - name: 'Install keepass menu launcher'
#   copy:
#     src: files/keepass/keepass.desktop
#     dest: /usr/share/applications/keepass.desktop
#     owner: root
#     group: root
#     mode: u=rw,g=r,o=r

    
