---

- name: 'Install layout-switcher dependencies'
  apt:
    package: ['x11-xkb-utils']
    state: present
    allow_unauthenticated: no
    update_cache: yes


- name: 'Install layout-switcher python dependencies'
  pip:
    name: pynput
    executable: pip3


- name: 'Configure layout-switcher autostart'
  become_user: '{{user}}'
  copy:
    src: '{{item}}'
    dest: ~/.config/autostart
    owner: '{{user}}'
    mode: u=rw,g=rw,o-rwx
  with_fileglob: '{{base_path}}/files/layout_switcher/LayoutSwitcher.desktop'
