---


- name: 'Install opera source list file'
  copy:
    src: files/opera/opera.list
    dest: /etc/apt/sources.list.d/opera.list


- name: 'Setup gpg key for opera'
  copy:
    src: files/opera/opera_pub_key.gpg
    dest: /usr/share/keyrings/opera_pub_key.gpg
    owner: 'root'
    mode: u=rw,g=r,o=r


- name: 'Install opera browser'
  apt:
    package: ['opera-stable']
    state: present
    allow_unauthenticated: no
    update_cache: yes


- name: 'Update opera launcher'
  copy:
    src: files/autostart/opera.desktop
    dest: /usr/share/applications/opera.desktop
    owner: 'root'
    mode: u=rw,g=r,o=r


- name: 'Install opera launcher'
  command: xdg-desktop-menu install --novendor /usr/share/applications/opera.desktop
  ignore_errors: yes
  when: linux_distro_name == 'ubuntu'


- name: 'Backup libffmpeg.so'
  become: true
  copy:
    src: /usr/lib/x86_64-linux-gnu/opera/libffmpeg.so
    dest: /usr/lib/x86_64-linux-gnu/opera/libffmpeg.so.bkp


- name: 'Replace libffmpeg.so'
  become: true
  copy:
    src: files/opera/libffmpeg.so
    dest: /usr/lib/x86_64-linux-gnu/opera/libffmpeg.so

