---

- name: 'Add apt key for opera'
  become: true
  apt_key:
    file: files/opera/opera_pub_key.gpg
    state: present


- name: 'Install opera source list file'
  copy:
    src: files/opera/opera.list
    dest: /etc/apt/sources.list.d/opera.list


- name: 'Install opera browser'
  apt:
    package: ['opera-stable']
    state: present
    allow_unauthenticated: no
    update_cache: yes


- name: 'Update opera launcher'
  become: true
  copy:
    src: '{{base_path}}/files/autostart/opera.desktop'
    dest: /usr/share/applications/opera.desktop
    owner: 'root'
    mode: u=rw,g=r,o=r


- name: 'Install xdg-desktop-menu'
  command: xdg-desktop-menu install --novendor /usr/share/applications/opera.desktop
  ignore_errors: yes
  when: linux_distro_name == 'ubuntu'
    